#!/usr/bin/env python3
# M2B06-scope_snapshot.py
#
# Purpose:
# - Scan master.xml for all unique sourceSystem + sourceModel combinations
# - Write a structured snapshot block (prefixed with #SNAPSHOT_) to run-scope.txt
# - Existing snapshot block is replaced on every run
# - Active SOURCE= entries in run-scope.txt are NEVER touched
#
# Output format in run-scope.txt (appended, commented):
#   # ==========================================================
#   # MASTER.XML SNAPSHOT - generated by M2B06
#   # Last updated: <timestamp>
#   # ==========================================================
#   #SNAPSHOT_SOURCE=archi
#   #SNAPSHOT_MODEL=R+Muni Architecture Modell.xml
#   #SNAPSHOT_SOURCE=bpmn
#   #SNAPSHOT_MODEL=BUP00-3rd Party Import.bpmn
#   # ... etc
#   # ==========================================================
#   # END SNAPSHOT
#   # ==========================================================
#
# Logs:
#   <root>/03-stages/99-logs/M2B06-scope_snapshot.log

from pathlib import Path
import xml.etree.ElementTree as ET
from datetime import datetime
import sys


# ----------------------------------------------------------
# CONFIG
# ----------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parents[2]

MASTER_XML = ROOT_DIR / "02-artifacts" / "00-xml" / "00-master" / "master.xml"
RUN_SCOPE  = ROOT_DIR / "03-stages" / "run-scope.txt"

LOG_DIR  = ROOT_DIR / "03-stages" / "99-logs"
LOG_FILE = LOG_DIR / "M2B06-scope_snapshot.log"

SNAPSHOT_START = "# SNAPSHOT_START"
SNAPSHOT_END   = "# SNAPSHOT_END"


# ----------------------------------------------------------
# Logging
# ----------------------------------------------------------

def log(msg: str):
    ts = datetime.now().isoformat(timespec="seconds")
    line = f"[{ts}] {msg}"
    print(line)
    with LOG_FILE.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def abort(msg: str):
    log(f"[ABORT] {msg}")
    sys.exit(1)


# ----------------------------------------------------------
# master.xml scannen
# ----------------------------------------------------------

def collect_snapshot_entries(master_root: ET.Element) -> list:
    """
    Sammelt alle eindeutigen (sourceSystem, sourceModel) Kombinationen
    aus master.xml. Sortiert nach sourceSystem, dann sourceModel.
    """
    seen = set()
    entries = []

    for el in master_root.iter():
        source_system = el.get("sourceSystem")
        source_model  = el.get("sourceModel")

        if not source_system or not source_model:
            continue

        key = (source_system, source_model)
        if key in seen:
            continue

        seen.add(key)
        entries.append({"sourceSystem": source_system, "sourceModel": source_model})

    entries.sort(key=lambda x: (x["sourceSystem"], x["sourceModel"]))
    return entries


# ----------------------------------------------------------
# run-scope.txt: Snapshot Block ersetzen
# ----------------------------------------------------------

def read_scope_without_snapshot(path: Path) -> list:
    """
    Liest run-scope.txt und gibt alle Zeilen OHNE den bestehenden
    Snapshot Block zurueck. Aktive SOURCE= Eintraege bleiben erhalten.
    """
    lines = path.read_text(encoding="utf-8").splitlines()

    result = []
    inside_snapshot = False

    for line in lines:
        if line.strip() == SNAPSHOT_START:
            inside_snapshot = True
            continue
        if line.strip() == SNAPSHOT_END:
            inside_snapshot = False
            continue
        if not inside_snapshot:
            result.append(line)

    # Trailing Leerzeilen am Ende entfernen
    while result and result[-1].strip() == "":
        result.pop()

    return result


def build_snapshot_block(entries: list, ts: str) -> list:
    """
    Baut den Snapshot Block als Liste von Zeilen.
    """
    lines = []
    lines.append("")
    lines.append(SNAPSHOT_START)
    lines.append("# ==========================================================")
    lines.append("# MASTER.XML SNAPSHOT - generated by M2B06-scope_snapshot.py")
    lines.append(f"# Last updated: {ts}")
    lines.append("# ==========================================================")
    lines.append("# Verfuegbare sourceSystem + sourceModel Kombinationen")
    lines.append("# im aktuellen master.xml (nur lesbar, nicht aktiv)")
    lines.append("# ==========================================================")

    current_system = None
    for entry in entries:
        if entry["sourceSystem"] != current_system:
            if current_system is not None:
                lines.append("#")
            current_system = entry["sourceSystem"]
            lines.append(f"# --- sourceSystem: {current_system} ---")

        lines.append(f"#SNAPSHOT_SOURCE={entry['sourceSystem']}")
        lines.append(f"#SNAPSHOT_MODEL={entry['sourceModel']}")

    lines.append("# ==========================================================")
    lines.append(SNAPSHOT_END)

    return lines


# ----------------------------------------------------------
# Main
# ----------------------------------------------------------

def main():
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    log("start M2B06 scope snapshot")

    if not MASTER_XML.exists():
        abort(f"master.xml missing: {MASTER_XML}")

    if not RUN_SCOPE.exists():
        abort(f"run-scope.txt missing: {RUN_SCOPE}")

    # master.xml laden
    try:
        master_tree = ET.parse(MASTER_XML)
        master_root = master_tree.getroot()
    except ET.ParseError as e:
        abort(f"cannot parse master.xml: {e}")

    # Snapshot Eintraege sammeln
    entries = collect_snapshot_entries(master_root)
    log(f"found {len(entries)} unique sourceSystem/sourceModel combinations")

    for e in entries:
        log(f"  {e['sourceSystem']:8} | {e['sourceModel']}")

    # run-scope.txt lesen ohne alten Snapshot
    base_lines = read_scope_without_snapshot(RUN_SCOPE)
    log(f"run-scope.txt base lines (without old snapshot): {len(base_lines)}")

    # Neuen Snapshot Block bauen
    ts = datetime.now().isoformat(timespec="seconds")
    snapshot_lines = build_snapshot_block(entries, ts)

    # Zusammenfuehren und schreiben
    final_lines = base_lines + snapshot_lines
    content = "\n".join(final_lines) + "\n"

    RUN_SCOPE.write_text(content, encoding="utf-8")
    log(f"run-scope.txt updated: {RUN_SCOPE}")

    log(f"M2B06 completed successfully | snapshot entries={len(entries)}")


if __name__ == "__main__":
    main()
